### ISSUE TITLE
EventTest.java:13: remove dummy test for cov checks

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/eo-events#38]
The puzzle `6-49a65616` from #6 has to be resolved: 

https://github.com/eo-cqrs/eo-events/blob/39372ce84e7198f0e9b3d82ee592a4bc6209aeb4/src/test/java/io/github/eocqrs/qce/EventTest.java#L13-L13

The puzzle was created by @rultor on 01-Jun-23. 

Estimate: 5 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
